### ISSUE TITLE
Handling of notes with encrypted sections

### ISSUE THREAD

**Issue by rbad** [Shampra/EvernoteToAnytype#43]
Many people I know who use Evernote encrypt parts of text within notes.

As it is impossible to search through all notes in Evernote to find which ones have at least one encrypted section, to then decrypt each permanently (to allow for importing to Anytype), it would be quite useful to find a way to import these notes as is, along with all other normal non-encrypted notes.

It should theoretically be possible as the encrypted parts are delineated within a note, as would a code block or table, so it could just be a matter of prompting the user for the encryption key to use.

The complication is that Evernote allows the use of more than one key for different notes, but typically a user does not use too many across their notebook (when I used Evernote I typically had three that I used depending on the notebook or level of sensitivity of the information). This complication could perhaps be rectified by taking a list of the few encryption keys from the user to try.

**Comment by Shampra** [comment]
Hi,

You can find all encrypt notes by searching "**encryption:"**

For the converter, it's not a problem to detect them. But I have to find how EN encrypt them (and how to decrypt them after that).

```
<en-crypt hint="toto" cipher="AES" length="128">RU5DMFFA...IdD0yK6oBpk=</en-crypt>
```

I have some encrypted notes, with a unique key. What about you?And people you know?  
Asking the password at start is easier to do than asking it for each notes.  
And probably some people have lots of encrypted notes with the same password and don't want to have to type it in every time.  
To make it suitable for everyone, it would lengthen the dev (especially since I'm going to run out of free time for a while), so it would be a step-by-step process, and we might as well meet as many needs as possible right from the start.

**Comment by rbad** [comment]
Good point on starting with the majority case, i.e. one global/common encryption key.

And thanks for the Evernote search tip; I was not aware it was possible!

**Comment by Shampra** [comment]
It seems that Evernote (at least v10) doesn't doesn't allow you to have ciphertext with different passwords.
This will simplify things :)

**Comment by Shampra** [comment]
In next release :
- you can choose a global password to unencrypt all crypted notes
- or you can request password entry for each encrypted note (default: disabled)

A text is added for easy retrieval of decrypted notes (as well as those that could not be decrypted, if applicable).
